<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Menu</name>
   <tag></tag>
   <elementGuidId>5c8a92ff-4ca0-43aa-a04f-35566efdecab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.ubermenu-responsive-toggle.ubermenu-responsive-toggle-main.ubermenu-skin-none.ubermenu-loc-.ubermenu-responsive-toggle-content-align-left.ubermenu-responsive-toggle-align-full</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Binod Bihari Mahto Koyalanchal University, Dhanbad'])[1]/following::a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>a >> internal:has-text=&quot;Menu&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9fd13621-5800-40dc-aa0c-cd0d6295b050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ubermenu-responsive-toggle ubermenu-responsive-toggle-main ubermenu-skin-none ubermenu-loc- ubermenu-responsive-toggle-content-align-left ubermenu-responsive-toggle-align-full </value>
      <webElementGuid>240c794e-d075-4461-8adc-4afb84f722b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ubermenu-target</name>
      <type>Main</type>
      <value>ubermenu-main-2</value>
      <webElementGuid>8e99d6c7-b527-45d9-b69a-ea3fd3e692d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Menu</value>
      <webElementGuid>fe44ee8d-52f9-4247-bbfd-7ec38b05b8cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;home page-template page-template-template-home page-template-template-home-php page page-id-4 siteorigin-panels  siteorigin-panels-home single-author&quot;]/section[@class=&quot;navbar-custom navi&quot;]/a[@class=&quot;ubermenu-responsive-toggle ubermenu-responsive-toggle-main ubermenu-skin-none ubermenu-loc- ubermenu-responsive-toggle-content-align-left ubermenu-responsive-toggle-align-full&quot;]</value>
      <webElementGuid>37796026-50d6-47e3-9438-9293b3797396</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Binod Bihari Mahto Koyalanchal University, Dhanbad'])[1]/following::a[1]</value>
      <webElementGuid>aa6caa48-d647-4f3a-83d8-ed52f1b6157f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='बिनोद बिहारी महतो कोयलांचल विश्वविद्यालय, धनबाद'])[1]/following::a[1]</value>
      <webElementGuid>6c07ccbc-5ae1-4110-b509-52599ffafbce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About Us'])[1]/preceding::a[2]</value>
      <webElementGuid>92601bd3-8297-4942-8aa5-634dc19d8e7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/a</value>
      <webElementGuid>7f7e2210-f952-41c0-b153-a47d57e31630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Menu' or . = 'Menu')]</value>
      <webElementGuid>b9692417-6cda-4320-a739-5562c94be675</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
