<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_PG ADMISSION NOTICE THROUGH SPECIAL DRI_31a40f</name>
   <tag></tag>
   <elementGuidId>c25910d4-2626-4b1d-bea3-5285324d1c7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tab3 > ul > li:nth-of-type(16) > a > div.thumbdesc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tab3']/ul/li[16]/a/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;PG ADMISSION NOTICE THROUGH SPECIAL DRIVE APPLICATION 2023. 12 Dec 2023&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>01a396fe-128d-4f12-a710-ba6bdd04983c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>thumbdesc</value>
      <webElementGuid>f85acd4b-171a-4bd2-a1af-2c8c3fb909e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PG ADMISSION NOTICE THROUGH SPECIAL DRIVE APPLICATION 2023. 12 Dec  2023 </value>
      <webElementGuid>51c354db-b7d8-44ac-9884-0458530da4be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab3&quot;)/ul[1]/li[16]/a[1]/div[@class=&quot;thumbdesc&quot;]</value>
      <webElementGuid>73f0f74e-78e8-4bc2-ab2a-9a4f4ec45d7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab3']/ul/li[16]/a/div[2]</value>
      <webElementGuid>7499a91f-0367-4955-975f-fa48908502e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Merit List of B.Pharm-H.G.E.A. College of Pharmacy, Chas, Bokaro.'])[1]/following::div[2]</value>
      <webElementGuid>540aa693-c462-47e2-94a6-89d7f452db69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Merit List of Certificate, Diploma and Advanced Diploma in Foreign...'])[1]/following::div[4]</value>
      <webElementGuid>26d7ab88-244d-4bc1-b437-f44140a260f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Induction Meet of P.G Sem 1 Students 2023-25.'])[1]/preceding::div[2]</value>
      <webElementGuid>69ae3119-939f-401e-8e20-c71dca76140f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ul/li[16]/a/div[2]</value>
      <webElementGuid>979aeaa1-a134-4639-9eb0-781ee8e809cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'PG ADMISSION NOTICE THROUGH SPECIAL DRIVE APPLICATION 2023. 12 Dec  2023 ' or . = 'PG ADMISSION NOTICE THROUGH SPECIAL DRIVE APPLICATION 2023. 12 Dec  2023 ')]</value>
      <webElementGuid>73f3d4ed-38da-469e-98d5-332fc45b344c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
