<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>font_Notice Regarding Postponement of Appli_358452</name>
   <tag></tag>
   <elementGuidId>5b7b70d5-3771-431c-839c-6d6a559ca6c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tab3 > ul > li:nth-of-type(20) > a > div.thumbdesc > font</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tab3']/ul/li[20]/a/div[2]/font</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Notice Regarding Postponement of Application for B.Pharma Course, Certificate, Diploma,... 7 Nov 2023&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>68a1b2fa-daa8-4696-9c86-ed6e3682246a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>my</name>
      <type>Main</type>
      <value>my</value>
      <webElementGuid>2a741664-c5c4-4943-bfe3-c8bacefc4583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Notice Regarding Postponement of Application for B.Pharma Course, Certificate, Diploma,...</value>
      <webElementGuid>b2fe6fe5-dfce-40a7-a7dc-63704941c827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab3&quot;)/ul[1]/li[20]/a[1]/div[@class=&quot;thumbdesc&quot;]/font[1]</value>
      <webElementGuid>a6378ead-a160-48d7-98e9-1d252d50eb55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab3']/ul/li[20]/a/div[2]/font</value>
      <webElementGuid>2aabf792-f956-4352-bb07-1e06272bac88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admission Notice for B.Pharma Course in HGEA College of Pharmacy.'])[1]/following::font[2]</value>
      <webElementGuid>9783475c-829b-49c6-bfe5-91297ff63ec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admission Notice-Certificate, Diploma &amp; Advance Diploma in Foreign Languages(German, French).'])[1]/following::font[4]</value>
      <webElementGuid>c4a2427d-8a1c-4fa3-9cf0-63c842351309</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quotation invitation for Annual maintenance of University Website.'])[1]/preceding::font[2]</value>
      <webElementGuid>4c30d341-03e0-458c-b6af-fa8c07d7e178</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regarding Quotation Invitation Notice for Identity Cards.'])[1]/preceding::font[4]</value>
      <webElementGuid>ee33d6e9-dcab-443e-abdb-98b3b3d066c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Notice Regarding Postponement of Application for B.Pharma Course, Certificate, Diploma,...']/parent::*</value>
      <webElementGuid>60415be2-8fa0-4c5d-8a99-163232efe291</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ul/li[20]/a/div[2]/font</value>
      <webElementGuid>c59b6436-b8d5-4426-8be4-ad94580423d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//font[(text() = 'Notice Regarding Postponement of Application for B.Pharma Course, Certificate, Diploma,...' or . = 'Notice Regarding Postponement of Application for B.Pharma Course, Certificate, Diploma,...')]</value>
      <webElementGuid>63242224-9cd6-4269-a6cf-3c8256c0f65a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
