<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>a43799c8-a6e6-446e-b94c-2fe2d6e3c25a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;BBMKU&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='BBMKU']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;BBMKU&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>20c39d42-aef3-4670-abea-d372a6960bd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://bbmku.ac.in/wp-content/themes/bbmku-child/images/logo.png</value>
      <webElementGuid>629316c5-b511-4819-b221-90905000beff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>BBMKU</value>
      <webElementGuid>7216e91e-be2a-4c42-93db-224128f5b3ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-template-default page page-id-68 page-parent single-author&quot;]/header[1]/a[1]/img[1]</value>
      <webElementGuid>3a5d15c7-00a1-4907-96cc-f4cac60cd3c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='BBMKU']</value>
      <webElementGuid>bb870920-705b-45c3-b1b9-4fa33c894a3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>1fa30ecf-8790-44d4-b4c3-9dbc7a6fb5eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://bbmku.ac.in/wp-content/themes/bbmku-child/images/logo.png' and @alt = 'BBMKU']</value>
      <webElementGuid>91a98071-f573-4bc6-a6e6-1b3da0685ed6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
