<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Academics_attachment-L size-L wp-post-image</name>
   <tag></tag>
   <elementGuidId>c14cf6e7-2f7f-4d1d-805c-b94318defbbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.attachment-L.size-L.wp-post-image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://bbmku.ac.in/wp-content/uploads/2018/09/logo-1.png')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.attachment-L >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d87c782d-d5bd-4dc2-9ffb-f5e18dae9b65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>232</value>
      <webElementGuid>b5c4e46f-0ac8-4eb4-924e-e870da2aeaf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>128</value>
      <webElementGuid>716f9ad1-f69a-491d-affd-f1b69dcbbeca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://bbmku.ac.in/wp-content/uploads/2018/09/logo-1.png</value>
      <webElementGuid>6f83e94e-c784-43a6-9f4c-51c8642018ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-L size-L wp-post-image</value>
      <webElementGuid>ed8bf91c-9403-4310-81e1-d3bbe4c1a283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-template-default page page-id-68 page-parent single-author&quot;]/footer[1]/div[@class=&quot;footer-list&quot;]/div[@class=&quot;footer-item&quot;]/img[@class=&quot;attachment-L size-L wp-post-image&quot;]</value>
      <webElementGuid>c2948128-b4f6-4e30-a925-959e55fb7627</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://bbmku.ac.in/wp-content/uploads/2018/09/logo-1.png')]</value>
      <webElementGuid>6e692fad-d0ba-4ca0-a0a4-85886890bf75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>0bf45755-db27-4278-99d6-2c5ba9381110</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://bbmku.ac.in/wp-content/uploads/2018/09/logo-1.png']</value>
      <webElementGuid>2e571bb3-b286-4c85-bafd-5f1585fdb339</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
