<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Programme of BABScBCom Sem-IV Exam (2017-20)</name>
   <tag></tag>
   <elementGuidId>aa0c041b-3fac-4774-a98f-746981fa2a21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.column-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tablepress-29']/tbody/tr/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=gridcell[name=&quot;Programme of BA/BSc/BCom Sem-IV Exam (2017-20)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>86e1f324-9580-46bb-971a-83e9b92f5e3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>column-2</value>
      <webElementGuid>599a28c8-6839-4be0-935c-4f3465a8b66b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Programme of BA/BSc/BCom Sem-IV Exam (2017-20)</value>
      <webElementGuid>e8a0caf4-24b5-40b3-af9e-15f695f66cff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tablepress-29&quot;)/tbody[@class=&quot;row-hover&quot;]/tr[@class=&quot;row-2 even&quot;]/td[@class=&quot;column-2&quot;]</value>
      <webElementGuid>fcbd9b0b-b2e2-4e0f-84ad-d1554a03d125</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tablepress-29']/tbody/tr/td[2]</value>
      <webElementGuid>86d150c2-6ae5-4b6a-b652-d39b1803da75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download'])[1]/following::td[2]</value>
      <webElementGuid>71bc5692-225e-4f60-8379-04c3d5c93083</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/following::td[2]</value>
      <webElementGuid>9fc33bd5-4bb6-4a71-b3d0-717f143abbb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download'])[2]/preceding::td[1]</value>
      <webElementGuid>fb1db313-c00c-4d46-86bc-d04d1f0da94a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Revised Programme of BA/BSc/BCom Sem-II Special Exam 2019'])[1]/preceding::td[3]</value>
      <webElementGuid>340e60c7-d235-443f-bafa-e344fae5761a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Programme of BA/BSc/BCom Sem-IV Exam (2017-20)']/parent::*</value>
      <webElementGuid>d3b198ad-ecd7-48ce-b545-fa32c157ec25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]</value>
      <webElementGuid>299b4663-42cc-48b6-b274-dc338407154d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Programme of BA/BSc/BCom Sem-IV Exam (2017-20)' or . = 'Programme of BA/BSc/BCom Sem-IV Exam (2017-20)')]</value>
      <webElementGuid>3f283df3-3911-4e8a-8f81-d98426b6afc1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
