<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Binod Bihari Mahto Koyalanchal University_4ea3cd</name>
   <tag></tag>
   <elementGuidId>94d8a373-321c-4253-997d-03fc8f1d81b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.ubermenu-icon.fas.fa-home</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-49']/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>22e20294-998c-45da-97b5-10ebf2a5d0f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ubermenu-icon fas fa-home</value>
      <webElementGuid>ddb54014-c719-446a-b330-9adc03854ab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-49&quot;)/a[@class=&quot;ubermenu-target ubermenu-target-with-icon ubermenu-item-layout-default ubermenu-item-layout-icon_left ubermenu-item-notext&quot;]/i[@class=&quot;ubermenu-icon fas fa-home&quot;]</value>
      <webElementGuid>963573e0-8840-43bd-9c95-a5400bc3251e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-49']/a/i</value>
      <webElementGuid>6b8625d8-03d2-4ecb-97dc-b015ba6293ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a/i</value>
      <webElementGuid>d7cee3e1-b8fa-47f8-88a8-1a6b2916c195</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-1982']/a/span[2]/i</value>
      <webElementGuid>85c58179-048c-473a-94df-aa85a5c8b7cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a/span[2]/i</value>
      <webElementGuid>394e3099-f57d-48e7-94ab-8eab433f6429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>fba4f378-771d-47e1-a9e4-b7ea7b4b3f89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
