<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_PG Semester III Result Available</name>
   <tag></tag>
   <elementGuidId>8ba6b0b8-57f0-4e1c-b16e-dd97869e0487</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#marquee-vertical > li:nth-of-type(4) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='marquee-vertical']/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;PG Semester III Result Available..&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0c196d5b-fa38-4832-abbd-b8761a1ffe4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>student/ug/result</value>
      <webElementGuid>fdc410ce-96a1-42c0-82b1-b343002c4148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PG Semester III Result Available..</value>
      <webElementGuid>01b91ba2-3ce2-4547-af3e-2a60aaf7635f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;marquee-vertical&quot;)/li[4]/a[1]</value>
      <webElementGuid>5a4eec0a-b815-4095-8c62-ca8981d287d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='marquee-vertical']/li[4]/a</value>
      <webElementGuid>fb6e5aa8-70c6-45f4-94ab-1f63e2fb4d4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exam-form Available'])[2]/following::a[1]</value>
      <webElementGuid>adab4351-c21c-4da7-8263-26ae1e731e09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PG Semester III']/parent::*</value>
      <webElementGuid>171367ff-c698-4708-ac0c-6165002c555f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'student/ug/result')]</value>
      <webElementGuid>1e9dd00d-a748-431a-97d0-85867a757df4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[4]/a</value>
      <webElementGuid>df844598-5db0-4ef7-9f5f-8bf19dd5c714</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'student/ug/result' and (text() = 'PG Semester III Result Available..' or . = 'PG Semester III Result Available..')]</value>
      <webElementGuid>ab29d1be-b40f-43b2-bd8f-648e598d6a2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
