<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Gallery_wp-image-8393</name>
   <tag></tag>
   <elementGuidId>8dde257b-3513-4a8d-a71e-aeaf8648d013</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.wp-image-8393</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-353']/div/ul/li[4]/figure/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.wp-image-8393</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7dbcda2e-f8f7-403c-81d8-d85146ef3ee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://bbmku.ac.in/wp-content/uploads/2024/02/WhatsApp-Image-2024-02-23-at-2.23.06-PM-1.jpeg</value>
      <webElementGuid>7f0f2f82-4108-4219-a36e-f4e74f0a13bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>8393</value>
      <webElementGuid>0d4015c3-cea6-4373-9b34-a60f0e839453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-link</name>
      <type>Main</type>
      <value>https://bbmku.ac.in/gallery/whatsapp-image-2024-02-23-at-2-23-06-pm-1/</value>
      <webElementGuid>98833f89-97d6-4434-a7df-67754fae6ffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wp-image-8393</value>
      <webElementGuid>ce6c505b-7615-4e56-81e6-785996237cae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-353&quot;)/div[@class=&quot;entry-content&quot;]/ul[@class=&quot;wp-block-gallery columns-0 is-cropped&quot;]/li[@class=&quot;blocks-gallery-item&quot;]/figure[1]/img[@class=&quot;wp-image-8393&quot;]</value>
      <webElementGuid>d6b85917-d1df-4f1c-9238-baf690e2d858</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-353']/div/ul/li[4]/figure/img</value>
      <webElementGuid>1a2c7670-484a-489c-830e-a61906cc19bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://bbmku.ac.in/wp-content/uploads/2024/02/WhatsApp-Image-2024-02-23-at-2.23.06-PM-1.jpeg')]</value>
      <webElementGuid>4c31a933-7c12-41e6-aa64-57c07fe7a790</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/figure/img</value>
      <webElementGuid>a198109d-c1f7-4328-869c-1875c07b1e4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://bbmku.ac.in/wp-content/uploads/2024/02/WhatsApp-Image-2024-02-23-at-2.23.06-PM-1.jpeg']</value>
      <webElementGuid>94491458-5216-4859-9277-59e268aaa75e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
