<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Gallery_wp-image-8391</name>
   <tag></tag>
   <elementGuidId>5c4b64ec-2076-4e9f-937e-25aa11c63969</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.wp-image-8391</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-353']/div/ul/li[2]/figure/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.wp-image-8391</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5ac6ae22-8f71-4c57-b362-18467da66bb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://bbmku.ac.in/wp-content/uploads/2024/02/WhatsApp-Image-2024-02-23-at-2.23.03-PM-2.jpeg</value>
      <webElementGuid>e7420fa3-2f52-4334-8f8d-266cbf98bdcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>8391</value>
      <webElementGuid>77b0569f-08f8-4e63-a8a7-ca0ac640211b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-link</name>
      <type>Main</type>
      <value>https://bbmku.ac.in/gallery/whatsapp-image-2024-02-23-at-2-23-03-pm-2/</value>
      <webElementGuid>4c1e4607-026c-40a6-b521-aa5986c3649d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wp-image-8391</value>
      <webElementGuid>3b007cbb-4828-4bd0-9daf-1587a991c0ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-353&quot;)/div[@class=&quot;entry-content&quot;]/ul[@class=&quot;wp-block-gallery columns-0 is-cropped&quot;]/li[@class=&quot;blocks-gallery-item&quot;]/figure[1]/img[@class=&quot;wp-image-8391&quot;]</value>
      <webElementGuid>3764c59d-ea3a-4396-a00d-2443dc0e2dcc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-353']/div/ul/li[2]/figure/img</value>
      <webElementGuid>a92ded17-d97b-4bf2-958c-6b0d376c986e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://bbmku.ac.in/wp-content/uploads/2024/02/WhatsApp-Image-2024-02-23-at-2.23.03-PM-2.jpeg')]</value>
      <webElementGuid>e6c6f339-236d-4ab2-a588-2ae7c69f90d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/figure/img</value>
      <webElementGuid>1f5589dc-d090-46c6-aca6-49ae025300f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://bbmku.ac.in/wp-content/uploads/2024/02/WhatsApp-Image-2024-02-23-at-2.23.03-PM-2.jpeg']</value>
      <webElementGuid>d27ed01f-15ed-4d7f-abce-db5a5875fd86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
