<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Gallery_attachment-L size-L wp-post-image_1_2_3_4_5</name>
   <tag></tag>
   <elementGuidId>c3b66f7b-7073-4934-849b-6dec3ad86009</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://bbmku.ac.in/wp-content/uploads/2018/09/NIRF2.gif')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(7) > .attachment-L</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8b317b34-5fc1-4ea0-826f-2b99d6266e6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>375</value>
      <webElementGuid>45a45eb3-4a92-4152-8d33-c0ce1f0ae647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>222</value>
      <webElementGuid>080b069b-993d-4cef-968d-50556d40d702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://bbmku.ac.in/wp-content/uploads/2018/09/NIRF2.gif</value>
      <webElementGuid>0ecfa79e-dd5b-476e-9d98-b71d246cb7a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-L size-L wp-post-image</value>
      <webElementGuid>e7526338-bb54-4a8d-904a-9e4bc11e8dd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-template-default page page-id-353 single-author&quot;]/footer[1]/div[@class=&quot;footer-list&quot;]/div[@class=&quot;footer-item&quot;]/img[@class=&quot;attachment-L size-L wp-post-image&quot;]</value>
      <webElementGuid>c938320b-13ce-46d6-b21f-bd3df05ee30d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://bbmku.ac.in/wp-content/uploads/2018/09/NIRF2.gif')]</value>
      <webElementGuid>443ba7b5-cd24-4978-90bb-bdc23c8b6ec2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/img</value>
      <webElementGuid>8d1cb7ed-dbff-45de-aaa6-0bd5d31baa63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://bbmku.ac.in/wp-content/uploads/2018/09/NIRF2.gif']</value>
      <webElementGuid>56acf5fb-3432-4dfe-a94c-4ae84311a7f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
