<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Gallery_wp-image-4349</name>
   <tag></tag>
   <elementGuidId>7dc78594-2815-4c2c-a778-7c09edfcde5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.wp-image-4349</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-353']/div/ul[2]/li[4]/figure/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>li:nth-child(4) > figure > a</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>822bf18b-6b8a-4d98-8903-9d99d110c8c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://bbmku.ac.in/wp-content/uploads/2021/10/image-1.jpeg</value>
      <webElementGuid>fd880641-3271-4f49-8729-2a156a528a05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>4349</value>
      <webElementGuid>b7969072-2134-4835-9a55-58e978f96a78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-link</name>
      <type>Main</type>
      <value>https://bbmku.ac.in/gallery/image-1/</value>
      <webElementGuid>02742584-9682-4809-8723-5f7a24422455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wp-image-4349</value>
      <webElementGuid>faf4fd02-52da-44db-afa7-b0e2802c5cbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://bbmku.ac.in/wp-content/uploads/2021/10/image-1.jpeg 651w, https://bbmku.ac.in/wp-content/uploads/2021/10/image-1-240x300.jpeg 240w</value>
      <webElementGuid>04386daa-2885-4537-842d-40e24a2dfbc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 651px) 100vw, 651px</value>
      <webElementGuid>b6c33cbc-3e65-4003-8104-d78b59907b71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-353&quot;)/div[@class=&quot;entry-content&quot;]/ul[@class=&quot;wp-block-gallery columns-8 is-cropped&quot;]/li[@class=&quot;blocks-gallery-item&quot;]/figure[1]/a[1]/img[@class=&quot;wp-image-4349&quot;]</value>
      <webElementGuid>038500d4-9c9e-4fcb-81ea-19e21b30a6e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-353']/div/ul[2]/li[4]/figure/a/img</value>
      <webElementGuid>ae359f8c-2176-47a7-8dfd-268af9298a93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://bbmku.ac.in/wp-content/uploads/2021/10/image-1.jpeg')]</value>
      <webElementGuid>86e24fba-b675-4675-848c-88b9422d2891</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/figure/a/img</value>
      <webElementGuid>fed161af-511b-42eb-b9fc-59ee828364a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://bbmku.ac.in/wp-content/uploads/2021/10/image-1.jpeg']</value>
      <webElementGuid>e379bb3c-9ef0-4b86-9e91-640aa49e31e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
