<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Gallery_wp-image-8390</name>
   <tag></tag>
   <elementGuidId>125f6c4e-b5bf-4e6a-bdf3-d0d6120e5f83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.wp-image-8390</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-353']/div/ul/li/figure/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.wp-image-8390</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>639abb5a-629f-4422-a6bc-ba97c312546a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://bbmku.ac.in/wp-content/uploads/2024/02/WhatsApp-Image-2024-02-23-at-2.23.03-PM-1.jpeg</value>
      <webElementGuid>49fd5471-71c8-49e7-a863-6549085c590e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>8390</value>
      <webElementGuid>dc0aa95d-277f-438c-bcd2-18f2e5ec47b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-link</name>
      <type>Main</type>
      <value>https://bbmku.ac.in/gallery/whatsapp-image-2024-02-23-at-2-23-03-pm-1/</value>
      <webElementGuid>43d16935-52ca-479c-96b8-678430848759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wp-image-8390</value>
      <webElementGuid>9ac48bd2-2eaa-4362-85e5-6557f7119b1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-353&quot;)/div[@class=&quot;entry-content&quot;]/ul[@class=&quot;wp-block-gallery columns-0 is-cropped&quot;]/li[@class=&quot;blocks-gallery-item&quot;]/figure[1]/img[@class=&quot;wp-image-8390&quot;]</value>
      <webElementGuid>dd7bc5f0-0c0a-455c-867d-07f9085bd6ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-353']/div/ul/li/figure/img</value>
      <webElementGuid>bd345c81-468d-4d22-8955-e87309bc33be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://bbmku.ac.in/wp-content/uploads/2024/02/WhatsApp-Image-2024-02-23-at-2.23.03-PM-1.jpeg')]</value>
      <webElementGuid>db750d15-ac10-413c-9223-c1911fb98ae9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//figure/img</value>
      <webElementGuid>139725a8-6af3-4076-b56d-88508c55eb2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://bbmku.ac.in/wp-content/uploads/2024/02/WhatsApp-Image-2024-02-23-at-2.23.03-PM-1.jpeg']</value>
      <webElementGuid>c5b2798b-f6e5-4792-834f-4e1bdd6ef7a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
