<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Gallery_wp-image-8396</name>
   <tag></tag>
   <elementGuidId>9bd4bb5d-72bb-4f2a-a343-6116bf81dd00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.wp-image-8396</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-353']/div/ul/li[7]/figure/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.wp-image-8396</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5278e981-8cd2-4fbb-ab13-73a8c74a63a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://bbmku.ac.in/wp-content/uploads/2024/02/WhatsApp-Image-2024-02-23-at-2.30.36-PM-10.jpeg</value>
      <webElementGuid>c314e2dc-8301-4a88-90c1-fdb3fabfd7e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>8396</value>
      <webElementGuid>d75bc95d-658d-4cf5-80fb-d2a080ff08cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-link</name>
      <type>Main</type>
      <value>https://bbmku.ac.in/gallery/whatsapp-image-2024-02-23-at-2-30-36-pm-10/</value>
      <webElementGuid>9e8000ab-a91d-4674-aa59-9d4cf1cccdb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wp-image-8396</value>
      <webElementGuid>4da94c84-7c0e-4d0d-926c-56520f680384</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-353&quot;)/div[@class=&quot;entry-content&quot;]/ul[@class=&quot;wp-block-gallery columns-0 is-cropped&quot;]/li[@class=&quot;blocks-gallery-item&quot;]/figure[1]/img[@class=&quot;wp-image-8396&quot;]</value>
      <webElementGuid>69bd4385-5ed5-49a0-98a9-51469ab2eefa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-353']/div/ul/li[7]/figure/img</value>
      <webElementGuid>54e86504-808b-42f1-9e90-05427f305e2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://bbmku.ac.in/wp-content/uploads/2024/02/WhatsApp-Image-2024-02-23-at-2.30.36-PM-10.jpeg')]</value>
      <webElementGuid>e78af4cf-d4e0-4297-8094-13755147e4f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/figure/img</value>
      <webElementGuid>11fb884a-33f7-48d8-9e53-8482164a9d98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://bbmku.ac.in/wp-content/uploads/2024/02/WhatsApp-Image-2024-02-23-at-2.30.36-PM-10.jpeg']</value>
      <webElementGuid>6ad29628-19e7-4491-95b9-026a9b26d157</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
