<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Gallery_wp-image-8392</name>
   <tag></tag>
   <elementGuidId>f47f745e-895e-45e5-bd33-fe6fe124a40f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.wp-image-8392</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-353']/div/ul/li[3]/figure/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.wp-image-8392</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>91e388ca-9bef-4a54-9a52-efea42c0e527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://bbmku.ac.in/wp-content/uploads/2024/02/WhatsApp-Image-2024-02-23-at-2.23.03-PM-3.jpeg</value>
      <webElementGuid>fdaa543e-71c5-4231-a137-ab9757129c19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>8392</value>
      <webElementGuid>5e4ab926-194c-4240-aaf6-7de350bd0806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-link</name>
      <type>Main</type>
      <value>https://bbmku.ac.in/gallery/whatsapp-image-2024-02-23-at-2-23-03-pm-3/</value>
      <webElementGuid>48d85861-6b63-4c57-8752-770fd480a14d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wp-image-8392</value>
      <webElementGuid>1db50c3b-f7d0-4c42-92a2-a88efa6142aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-353&quot;)/div[@class=&quot;entry-content&quot;]/ul[@class=&quot;wp-block-gallery columns-0 is-cropped&quot;]/li[@class=&quot;blocks-gallery-item&quot;]/figure[1]/img[@class=&quot;wp-image-8392&quot;]</value>
      <webElementGuid>a2b2b7e9-7ac1-4388-bf58-95345c6cd9e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-353']/div/ul/li[3]/figure/img</value>
      <webElementGuid>f40148b1-0483-4338-a268-99f3b4a80e89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://bbmku.ac.in/wp-content/uploads/2024/02/WhatsApp-Image-2024-02-23-at-2.23.03-PM-3.jpeg')]</value>
      <webElementGuid>3998c29e-35b4-4d00-b29b-999594b59db4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/figure/img</value>
      <webElementGuid>81180908-049c-452f-8ec1-edf94c52dd61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://bbmku.ac.in/wp-content/uploads/2024/02/WhatsApp-Image-2024-02-23-at-2.23.03-PM-3.jpeg']</value>
      <webElementGuid>dd58beb1-280f-4cde-a8ab-e95774e6d842</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
